version: '3.0'
services:
    container:
        build:
            context: '.'
            dockerfile: Dockerfile
        volumes:
            - '.:/workspace/coms4156'
        ports:
            - '3000:3000'
            - '8001:8001' # redoc
        command: 'tail -f /dev/null'
        depends_on:
            - database
            - elastic
        links:
            - database
            - elastic
        environment:
            DB_HOST: database
            DB_PORT: 3306
            DB_USER: blogly
            DB_PASSWORD: blogly
            DB_NAME: blogly
            OAUTH20_CLIENT_ID: 552600159087-4edffngila0707hhrbk2rqt9gubej71r.apps.googleusercontent.com
            OAUTH20_CLIENT_SECRET: AuVbVMRuczPnLycVNBt4lik8
            EXPRESS_SESSION_KEY: keyboard cat
            TWILIO_CLIENT_ID: ACada91a1ae88de654007413c58037070c
            TWILIO_CLIENT_SECRET: fb468e65cd013045ae21b100d9fb177b
            TWILIO_PHONE_NUMBER: '+19198137840'
    database:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: blogly
            MYSQL_USER: blogly
            MYSQL_PASSWORD: blogly

    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        container_name: es
        environment:
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
            - 'discovery.type=single-node'
            - 'http.cors.enabled=true'
            - 'http.cors.allow-origin=https://app.elasticvue.com'
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
volumes:
    db_data: {}
