version: '3.0'
services:
    container:
        build:
            context: '.'
            dockerfile: Dockerfile
        volumes:
            - '.:/workspace/coms4156'
        ports:
            - '3000:3000'
            - '8001:8001' # redoc
        command: 'tail -f /dev/null'
        depends_on:
            - database
        links:
            - database
        environment:
            DB_HOST: database
            DB_PORT: 3306
            DB_USER: blogly
            DB_PASSWORD: blogly
            DB_NAME: blogly
            OAUTH20_CLIENT_ID: 552600159087-4edffngila0707hhrbk2rqt9gubej71r.apps.googleusercontent.com
            OAUTH20_CLIENT_SECRET: AuVbVMRuczPnLycVNBt4lik8
            EXPRESS_SESSION_KEY: keyboard cat
            TWILIO_CLIENT_ID: AC74840a5c26ac26c26fd7e16d2a10a7ea
            TWILIO_CLIENT_SECRET: D155981098e0cdfb839d9a54783bbdf3
            TWILIO_PHONE_NUMBER: '+18509192681'
    database:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: blogly
            MYSQL_USER: blogly
            MYSQL_PASSWORD: blogly
volumes:
    db_data: {}
