version: '3.8'
services:
    container:
        build:
            context: '.'
            dockerfile: Dockerfile
        volumes:
            - '.:/workspace/coms4156'
        ports:
            - '3000:3000'
        command: 'tail -f /dev/null'
