CREATE TABLE IF NOT EXISTS user (
    uuid INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(40) NOT NULL,
    passwordHash VARCHAR(32) NOT NULL,
    name VARCHAR(60) NOT NULL,
    description TEXT,
    notificationPreference VARCHAR(10) NOT NULL -- to be determined
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS blog (
    uuid INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    author INT UNSIGNED NOT NULL,
    created DATETIME NOT NULL,
    updated DATETIME NOT NULL,
    content TEXT,
    FOREIGN KEY (author) REFERENCES user(uuid) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS follow (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
    follower INT UNSIGNED NOT NULL,
    followee INT UNSIGNED NOT NULL,
    FOREIGN KEY (follower) REFERENCES user(uuid) ON DELETE CASCADE,
    FOREIGN KEY (followee) REFERENCES user(uuid) ON DELETE CASCADE
) ENGINE = InnoDB;